// The MIT License (MIT)
//
// Copyright (c) 2020 Collin Johnson/FRC Team 3656
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Dart Packages
import 'package:bloc/bloc.dart';

// Flutter Packages
import 'package:flutter_bloc/flutter_bloc.dart';

/// [CheckboxFormElementEvent] represents an event that has happened on the frontend.
///
/// [CheckboxFormElementEvent.toggleCheck] describes an event where the status
/// of the [Checkbox] contained in [CheckboxFormElement] has changed state.
/// True -> False, False -> True in this case.
enum BooleanDataBlocEvent { toggleBoolean, setTrue, setFalse }

/// [BooleanDataBloc] is the BLoC class for [CheckboxFormElement].
///
/// This [Bloc] contains the state of a [CheckboxFormElement] widget form
/// element asynchronously. The Bloc is fed an event that has occurred, and
/// the Bloc responds with the new state that is algorithmically generated by
/// the business logic contained.
class BooleanDataBloc extends Bloc<BooleanDataBlocEvent, bool> {
  /// Constructs a [BooleanDataBloc].
  ///
  /// This is a default constructor that has an initial state of false if not
  /// provided with initial state.
  /// [initialState] - Optional Argument that specifies what state to begin
  /// with.
  BooleanDataBloc({bool initialState: false}) : super(initialState);

  /// [mapEventToState] maps an incoming UI event to a new state change.
  ///
  /// This is an asynchronous factory that allows for UI processing and
  /// rendering alongside data and backend management. This method is where all
  /// of the business logic is executed.
  @override
  Stream<bool> mapEventToState(BooleanDataBlocEvent event) async* {
    switch (event) {
      case BooleanDataBlocEvent.toggleBoolean:
        yield !state;
        break;
      case BooleanDataBlocEvent.setTrue:
        yield true;
        break;
      case BooleanDataBlocEvent.setFalse:
        yield false;
        break;
    }
  }
}
