/*
The MIT License (MIT)

Copyright (c) 2020 Collin Johnson/FRC Team 3656

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */

/// [NamespacedKey] is an alternative to using unique ids for elements.
///
/// [NamespacedKey] has two important elements - the namespace, and the key.
/// The namespace is a group of related ideas, a module, or package.
/// The key is the id of a certain individual in a group, module, or package.
class NamespacedKey {
  /// [namespace] is a group, module, or package.
  String namespace;

  /// [key] is a name of an individual object within a group, module, or package.
  String key;

  /// Args constructor with expected arguments, namespace and key.
  NamespacedKey(this.namespace, this.key);

  /// [fromJson] is an autogenerated json mapping parser that takes a json object and constructs a NamespacedKey object.
  NamespacedKey.fromJson(Map<String, dynamic> json, this.namespace, this.key) {
    namespace = json['namespace'];
    key = json['key'];
  }

  /// [toJson] is an autogenerated json mapping generator that takes a NamespacedKey object and creates a json object.
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['namespace'] = this.namespace;
    data['key'] = this.key;
    return data;
  }

  /// Custom toString() method for serializing the object for debugging purposes.
  @override
  String toString() => '$namespace:$key';
}
